"""empty message

Revision ID: e31451062987
Revises: 
Create Date: 2020-02-10 23:35:20.239696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e31451062987'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Artist',
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('artist_name', sa.String(), nullable=True),
    sa.Column('artist_city', sa.String(length=120), nullable=True),
    sa.Column('artist_state', sa.String(length=120), nullable=True),
    sa.Column('artist_phone', sa.String(length=120), nullable=True),
    sa.Column('artist_genres', sa.String(length=120), nullable=True),
    sa.Column('artist_image_link', sa.String(length=500), nullable=True),
    sa.Column('artist_facebook_link', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('artist_id')
    )
    op.create_table('Venue',
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('venue_name', sa.String(), nullable=True),
    sa.Column('venue_city', sa.String(length=120), nullable=True),
    sa.Column('venue_state', sa.String(length=120), nullable=True),
    sa.Column('venue_address', sa.String(length=120), nullable=True),
    sa.Column('venue_phone', sa.String(length=120), nullable=True),
    sa.Column('venue_image_link', sa.String(length=500), nullable=True),
    sa.Column('venue_facebook_link', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('venue_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Venue')
    op.drop_table('Artist')
    # ### end Alembic commands ###
